### ISSUE TITLE
how to set permissions of google play service permanently

### ISSUE THREAD

**Issue by afshinnajafi** [jomo/fix_open_gapps_permissions#1]
hi 

i use your script and fixed "Google play service has stopped" error !  but after factory reset my device that error has come again !  how to set permissions permanently ? 

my device : samsung a5108 android 6.0.1

**Comment by jomo** [comment]
This needs to be fixed in the ROM (see [here](https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a)), otherwise you need to run this script after resetting your device.
